### PR TITLE
global: support for user-defined processing actions and more

### PR DESCRIPTION
**Pull request by jalavik**
Replaces #29

### CODE REVIEW

**Comment by jalavik** [comment]
@tiborsimko @jirikuncar This one is ready to go in so it would be great if you could merge it. The quantified code issues are minor and existed mostly from before.

**Comment by PXke** [comment]
Hey @jalavik what do we need to make it go in master :) ?

**Comment by jalavik** [comment]
@PXke Nothing major. Its ready. Only thing is that it seems Python 2.6 has a problem with `pydocstyle`. Gonna check that quick.

**Comment by jalavik** [comment]
@jirikuncar @lnielsen Ready to go.

**Comment by kaplun** [comment]
Ok. I think this is ready to be merged. 
@romanchyla just a heads-up on this big PR that we need for INSPIRE and TIND: given the large amount of changes this will be released as 2.0.0

**Pull request merged**
